package com.apigit.enums;

public enum ComponentEnum {
    CONTATOS,
    CONTATOS_RECORRENTES
    , CONTATOS_COM_MAIS_RECORRENCIA
    , MENSAGENS_ATIVAS_ENVIADAS
    , MENSAGENS
    , CANAIS
    , FLUXO_CONVERSACIONAL
    , BLOCOS_COM_MAIS_EXCECAO
    , BLOCOS_COM_MAIS_TRANSBORDO
}
